### ISSUE TITLE
Have bot greet new Discord members

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RABot#21]
Have the bot send a PM to new Discord members that tells them how to get verified and why. I can make a write up something for this or make a gif, if you decide to code it.

**Comment by vzapo** [comment]
Hi guys,

I've implemented this but would need a better message to send to the user :)
Currently upon joining it dm's you:
```
Hello ${member.displayName}. Welcome to RetroAchievemenets.org community. Please verify your account by sending a direct message to anyone of the @mod team and they will help you with the process
```
@kdecks can you provide some input on the message ? if it's ok or something more should be added?

**Comment by meleu** [comment]
@vzapo 
The message can be this one:
```
Hello ${member.displayName}. Welcome to RetroAchievemenets.org Discord server. Please verify your account by sending a message to RAdmin on the website asking to be verified.
<https://retroachievements.org/user/RAdmin>
```
