### ISSUE TITLE
make self roles management via reactions

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RABot#32]
I've just stumbled upon [ZiraDiscord bot](https://github.com/ZiraDiscord/Zira) and I want to make it on RABot too.

Seems simpler for the users than having to type commands.

**Comment by kdecks** [comment]
carl.gg I currently doing this on our server, obviously if RAbot can do it it'd be nice.

**Comment by vzapo** [comment]
I was thinking of something like that also. emulating carl.gg functionality into RAbot would be a nice feature and having one bot to manage things would be easier.

**Comment by meleu** [comment]
we're using carl
