### ISSUE TITLE
Feature Request: Custom mastery messages for specific games

### ISSUE THREAD

**Issue by rabbids4eva** [RetroAchievements/RABot#4]
I would like a feature for developers to add their own mastery messages for specific games. Games so far include the NES and SNES burn-ins, Mario Series, Final Fantasy series and Color a Dinosaur.

For example:

"Yabba-Dabba-Doo! [User] has mastered The Flinstones for Master System!"

"[User] has mastered Kaboom! for Atari 2600! Three cheers for the bucket brigade!"

"[User] has kicked some tail and mastered Gex 3: Deep Cover Gecko for N64!"

**Comment by meleu** [comment]
Since the site's feed is :ded:, I'm closing this issue.
We can reopen it later (v2:tm:)
