### ISSUE TITLE
Value to Time Command

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RABot#40]
I would like to have a command which can be used to get the time in either ''Milliseconds'' or Frames. I tried to find something in the internet but couldn't find anything I would like to use. I want a command where I can say which time format it uses and if I type something like:
`!command frames 0x11e0`
the bot answers with an output like
`4576 Frames have the Time 1:16.26`

Also it should be possible to type
`!command frames 1:16.26`
and get the answer
`The Time 1:16.26 has 4576 Frames`

Same with site Millisecs format (100 = 1sec) and if possible with Hex and Dec format support. It can be used to get timer value from memory easier  by searching for exact numbers and it's also easier to create default times for leaderboards. Also it could help to fix broken leaderboards.

**Comment by meleu** [comment]
I'm on it.
Do you think we should always default the amount of frames per second to 30 or make it customizable?

**Comment by SporyTike** [comment]
If you can do it I would like a custom mode, not just 30. For example once I had a timer which counted and had to be divided by 4 to be correct. I thought it would be too much to ask for such a customomization. If you find a way to do it, please do it so it can also be used like
`!command 60 0x11e0` or `!command custom<60> 0x11e0`
About the 30 as default, I don't really know what the most used runtime on the site is. I would use 30 or 60, depending on which is used more often.
