### ISSUE TITLE
define a Coding Style

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RABot#46]
When I started RABot I wasn't a "JavaScript guy" and never cared that much about the coding style. I just followed what I used to do with C code mixed with old RAWeb's PHP code, which also doesn't have a defined styled...

It turns out that now I'm not happy with my own JS coding style here and I'm noticing RABot's code is becoming a bit messy.

After googling about JavaScript coding styles the one I liked most is this one from airbnb:
https://github.com/airbnb/javascript

I would like to know your opinions @vzapo and @luchaos (but please, do not suggest using a semicolon-less style).

**Comment by luchaos** [comment]
thanks for doing that @meleu @vzapo 👍
may i propose going for the full airbnb style right away? it‘s the one that was set up for v2‘s frontend, too. this way it could be the norm all across ra‘s js code.
semicolons is fine by me :) just, i‘m more used to single quotes from the psr and airbnb styles. not too strong of an opinion on that.

just realized i omitted those semicolons in raweb :/ i‘ll clean that up by adding the same config there as well.

**Comment by vzapo** [comment]
yeah cool with me, i will integrate the airbnb style and relinter the code according to their guides

**Comment by meleu** [comment]
> just, i‘m more used to single quotes from the psr and airbnb styles

same here

**Comment by meleu** [comment]
All right... I took the courage to change the indentation to 2 spaces. Let's stick with the airbnb coding style.

Closing this.
