### ISSUE TITLE
Simplify !rules command

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RABot#49]
Namely, change it to link to the code of conduct only.

**Comment by vzapo** [comment]
That would be a good idea, i'll take a look at it.

**Comment by meleu** [comment]
@kdecks what's wrong with the simplified version?

**Comment by vzapo** [comment]
don't think it's something wrong but a simpler message pointing out to the full user conduct potentially could be more efficient. the user would just read all the conduct straight,after all that's why it's there :)

**Comment by meleu** [comment]
I hardly believe average users would read that whole text.

If they are not being a dick, not sharing copyrighted material, and keeping the channels on topic, it's all fine.

I disagree with the change proposed here and maybe it's better to wait for an admins/mods consensus before submitting a PR.

**Comment by meleu** [comment]
I'm going to edit the "simple rules" as discussed in the mods channel.
