### ISSUE TITLE
meme board moderation

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RABot#50]
@vzapo it's great to have the RA Meme System:tm: accepting new entries again, thanks for that! :heart: 

But I noticed that the mod reaction with :no_entry_sign: isn't working as it was when I implemented it.

The idea is when a mod react to a message with :no_entry_sign::
- if a message isn't on the memeboard yet, it won't be, no matter how many :robot: reactions it has
- if a message is already on the memeboard, it'll be deleted.

**Comment by vzapo** [comment]
hmm ok, got the idea:) i'll take a look at it and see how can it be fixed.

**Comment by vzapo** [comment]
the  no_entry_sign  is only working if falgged by mod as this is how i understood it should work ? that;s how i pushed the fix ...
