### ISSUE TITLE
Suggest new entries for memefacts

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RABot#6]
Rules to suggest new entries for `!memefact`:
- you can't suggest your own quote
- when suggesting a quote, be sure to get an approval from the author and/or the person being mentioned.

The current ones are here:
https://github.com/RetroAchievements/RABot/blob/master/assets/json/memefacts.json

---

I plan to later change the memefacts to a "starboard".
Inspiration: https://anidiots.guide/coding-guides/making-your-own-starboard

**Comment by Keltron3030** [comment]
@Jon (ikki5), You may not use the memefact command again for another 24.5 seconds. - RA Bot

**Comment by rabbids4eva** [comment]
What's better than earning cheevos? Earning cheevos on HARDCORE!

Common people get score on Softcore, Awesome people get TWICE the score on Hardcore.

If in doubt, use RetroArch.

What time will my daughter be home!?

Laura! LAURA!

**Comment by Thestret00** [comment]
I honestly can't come up with anything decent, so I'll just give up.

Bot is broken? no way you're doing something wrong :kappaz:

To be fair, you have to have a very high IQ to understand Color a Dinosaur. The gameplay is extremely nuanced, and without a solid grasp the intricate mechanics most of the enjoyment will go over a typical viewer's head. There's also the color palette great variety of colors, which is majestically applied into the canvas- every single pattern reminiscences of the ones used on greek mithology, , for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the depths of the gameplay, to realize that it's not just fun- they say something deep about LIFE. As a consequence people who dislike Color a Dinosaur truly ARE idiots- of course they wouldn't appreciate, for instance, the appeal in Color a Dinosaur's feelings that of a fully finished Brontosaurus gives, which is full of rigorous and complex emotions most of them which are close enough for a human being to reach enlightenment, and fulfillment of a life's worth achievement. I'm smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as FarSights Studios's genius wit unfolds itself on their CRT screens. What fools. how I pity them. :sexyaf:
And yes, by the way, i DO have a CaD tattoo. And no, you cannot see it. It's for the ladies' eyes only- and even then they have to demonstrate that they're within 5 IQ points of my own (preferably lower) beforehand. Nothin personnel kid.

Soon(tm)

*Licks the chat* - meowmixery

Calling me toxic is a banneable offense

#crazydesertpartybusadinosaur97 is, in fact, the most premium and sekrit channel in this very server, and only the cool kids can enter :kappaz:

**Comment by Blazekickn** [comment]
-"no fun allowed" - kdecks

suprised it wasn't in there already tbh

**Comment by Blazekickn** [comment]
-@everyone

**Comment by CoolCanuck** [comment]
"RIP Dexterspet" 

(how did we not think about this before?)


and 
![image](https://user-images.githubusercontent.com/15615155/47050116-3a075680-d16d-11e8-9a88-b9d8abdb0430.png)

**Comment by Keltron3030** [comment]
I don't cry blood, I extend the gore. - Salsa

**Comment by Danver2618** [comment]
"Don't trust anything shika says" - kdecks

**Comment by CoolCanuck** [comment]
“I take pride in my piracy”
-Blazekickn

**Comment by meleu** [comment]
party is over! :triumph:

Later I'll think on a better way to handle the best quotes of our community. Thanks for your comprehension, guys.

**Comment by Keltron3030** [comment]
Dead link on top

**Comment by CoolCanuck** [comment]
I can't believe we got rid of memefacts, now the bot is pretty boring.... legitimately really boring :( 
And I'm going to keep suggesting things so 🤷‍♂️ 


"If we don't got it, you don't want it."   -Viral

**Comment by meleu** [comment]
alright dudes, `memefact` is back.
**HOWEVER**, when suggesting new entries, consider these two rules:
- you can't suggest your own quote
- when suggesting a quote, be sure to get an approval from the author and/or the person being mentioned.

**Comment by ViperZang** [comment]
`私はモンスターのお尻からジャガイモを食べる (I eat potatoes from a monster's ass) - televandalist and Google Translate`
![monster-potatoes-permission](https://user-images.githubusercontent.com/31069034/47624187-17bbf400-daf0-11e8-841e-b519c7d24512.png)

**Comment by ViperZang** [comment]
`"I HEREBY GIVE YOU PERMISSION TO POST ANYTHING I SAID PUBLICALLY HERE" - CoolCanuck`
![you-asked-for-it](https://user-images.githubusercontent.com/31069034/47625046-da0f9900-daf8-11e8-9292-906cfe89ffde.png)

**Comment by coolscribble** [comment]
![obrazek](https://user-images.githubusercontent.com/43485409/47625329-b4988480-db24-11e8-8ee6-a28ba17e8ed0.png)

**Comment by Danver2618** [comment]
"sleep is for the weak" - Theztret00

**Comment by Danver2618** [comment]
"I mastered <any game>:wolf:" - GOGZero

**Comment by kdecks** [comment]
@meleu you suggested something very similar to this before, but I'd like a very simple way for users to nominate memefacts. My idea is if they respond with both 🤖 ❤️, that it will be logged (somewhere). And then I or another mod can go through the list of all nominated from time to time and check with person quoted, and then add them here to the git list.

**Comment by meleu** [comment]
That would be a cool feature, indeed. But would require a more :sophisticated: coding, and I'm currently trying to stay immersed in PHP/laravel stuff. But, yeah, it's on my todo list.

By the way, I also want to allow mods to add fun/meme facts via commands, directly on discord (no need to handle this via github). But it's for the future.

**Comment by Keltron3030** [comment]
What sorcery is this - televandalist

**Comment by televandalist** [comment]
"I can be slow sometimes." - Rimsala

**Comment by televandalist** [comment]
"Zaphnath is typing..." - Server

**Comment by televandalist** [comment]
or...

"what's tl;dr" - Zaphnath

**Comment by meleu** [comment]
@televandalist keep the rules in mind (specially the second one):

- you can't suggest your own quote
- when suggesting a quote, be sure to get an approval from the author and/or the person being mentioned.

**Comment by televandalist** [comment]
"What? That's easy." - TheBatman

Permission granted: https://i.lensdump.com/i/AP1FfH.png

**Comment by meleu** [comment]
I've changed the RABot's "meme system". Reposting what I posted in the #community-news:

---

<@&377399304106541058>
Hello peeps. Today we're starting a new "meme system" on this server. Here's how it works:

- when you see a "memeable" message, react to it with a 🤖.
- **keep in mind our Code of Conduct**, cause it still applies. So don't use the meme system to offend people (summing up: don't be a dick).
- when a message reaches 5 🤖s in reactions (author's reaction doesn't count), the RABot promotes it to a meme and it goes to our #meme-board.
- bot messages are not memeable.
- if a mod reacts to a message with 🚫, it becomes "unmemeable" (and if it's already on #meme-board, it'll be deleted).
- you can get a random meme by using the `!meme` command, or a specific one using `!meme N`, where `N` is the meme number.
- as usual: if you feel offended report it to a mod.

**Comment by meleu** [comment]
I'll keep this issue open for a while, so we can post links to the memeable messages. And then people can go to the message and react with a :robot:

I'm starting with some of the previous list:

"I'm legally not allowed to speak on that subject" - Dexsterspet
https://discordapp.com/channels/310192285306454017/464947132017803284/506278962134253568

"What sorcery is this?" - televandalist
https://discordapp.com/channels/310192285306454017/509126629600002080/514629624496652288

"I can be slow sometimes." - Rimsala
https://discordapp.com/channels/310192285306454017/310195377993416714/507353007927721984

"i'm the purest of virgins in this regard" - Maluno
https://discordapp.com/channels/310192285306454017/453242743292952578/523465220430102528

"The Pumpkin King event sucks" - muskn
https://discordapp.com/channels/310192285306454017/368501573388730378/370722807765663744

"It's intentional" - meleu
https://discordapp.com/channels/310192285306454017/310195377993416714/502947915942068274

"that's not retro, admons, please ban! hammer" - meleu
https://discordapp.com/channels/310192285306454017/453242743292952578/501516202032627726

"yeah, kdecks is right" - meleu
https://discordapp.com/channels/310192285306454017/310195377993416714/503641714117050389
