### ISSUE TITLE
Calc command can't use comma

### ISSUE THREAD

**Issue by SporyTike** [RetroAchievements/RABot#60]
The calc command can use non-full numbers by putting a point in the number (e.g. `1.25` (5/4)). In some languages it is common to use a comma instead of a dot so the number looks like `1,25`.

At the moment if you type or paste in a number with comma you get an error that the message can't be read including which char is wrong and you need to correct the comma. It would be nice to see that the bot accepts the comma and transforms it to a dot automatically before the calculation.

**Comment by lowlightdev** [comment]
Hey, will take a look at it.
