### ISSUE TITLE
Feature Request - Commands for Tickets

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RABot#66]
Would like to see some commands for ticket info. Some examples:

- For seeing ticket totals per game: `!gametickets 341` (341 being the game ID)
>  [**Final Fantasy III (U) | Final Fantasy VI (J) (SNES)**](https://retroachievements.org/Game/341)
> *Total Open Tickets:* [56](https://retroachievements.org/ticketmanager.php?g=341&t=2041)
> *Total Closed Tickets:* [26](https://retroachievements.org/ticketmanager.php?g=341&t=2042)
> *Total Resolved Tickets:* [68](https://retroachievements.org/ticketmanager.php?g=341&t=2044)
> *Overall Total Tickets:* [150](https://retroachievements.org/ticketmanager.php?g=341&t=2047)

- For seeing ticket totals per achievement: `!achtickets 6001` (6001 being the ach ID)
> [**The World is Yours**](https://retroachievements.org/Achievement/6001)
> *Total Open Tickets:* [6](https://retroachievements.org/ticketmanager.php?a=6001&t=2041)
> *Total Closed Tickets:* [3](https://retroachievements.org/ticketmanager.php?g=341&a=6001&t=2042)
> *Total Resolved Tickets:* [6](https://retroachievements.org/ticketmanager.php?g=341&a=6001&t=2044)
> *Overall Total Tickets:* [15](https://retroachievements.org/ticketmanager.php?g=341&a=6001&t=2047)

- For seeing a user's current open tickets: `!usertickets televandalist`
> [**televandalist**](https://retroachievements.org/user/televandalist)
> *Total Open Tickets:* [1](https://retroachievements.org/ticketmanager.php?u=televandalist&t=2041)
> *Total Closed Tickets:* [114](https://retroachievements.org/ticketmanager.php?u=televandalist&t=2042)
> *Total Resolved Tickets:* [332](https://retroachievements.org/ticketmanager.php?u=televandalist&t=2044)
> *Overall Total Tickets:* [447](https://retroachievements.org/ticketmanager.php?u=televandalist&t=2047)

- For seeing ten most recent tickets: `!tickets recent`
>[**29194**](https://retroachievements.org/ticketmanager.php?i=29194) - [Adding Fuel to the Fire](https://retroachievements.org/Achievement/34613) - Developer: [MeCKooLL](https://retroachievements.org/User/MeCKooLL) - Reporter: [Ragengow](https://retroachievements.org/User/Ragengow) - 27 Jun 2020, 17:55
>[**29193**](https://retroachievements.org/ticketmanager.php?i=29193) - [Gambling Addict](https://retroachievements.org/Achievement/108181) - Developer: [Blazekickn](https://retroachievements.org/User/Blazekickn) - Reporter: [Jdk2222](https://retroachievements.org/User/Jdk2222) - 27 Jun 2020, 17:24
> etc.

- For seeing ten most reported games: `!tickets most`
>[**Final Fantasy Tactics Advance**](https://retroachievements.org/Game/519) - [76](https://retroachievements.org/ticketmanager.php?g=519)
>[**Final Fantasy III (U) | Final Fantasy VI (J)**](https://retroachievements.org/Game/341) - [56](https://retroachievements.org/ticketmanager.php?g=341)
>[**Golden Sun**](https://retroachievements.org/Game/767) - [47](https://retroachievements.org/ticketmanager.php?g=767)
>[**Harvest Moon**](https://retroachievements.org/ticketmanager.php?f=1) - [34](https://retroachievements.org/ticketmanager.php?g=934)
>[**Legend of Zelda, The: The Minish Cap**](https://retroachievements.org/Game/559) - [34](https://retroachievements.org/ticketmanager.php?g=559)
>[**Faxanadu**](https://retroachievements.org/Game/1682) - [22](https://retroachievements.org/ticketmanager.php?g=1682)
>[**Rhythm Tengoku**](https://retroachievements.org/Game/4033) - [16](https://retroachievements.org/ticketmanager.php?g=4033)
>[**Gradius III**](https://retroachievements.org/Game/342) - [16](https://retroachievements.org/ticketmanager.php?g=342)
>[**Super Mario RPG**](https://retroachievements.org/Game/471) - [13](https://retroachievements.org/ticketmanager.php?g=471)
>[**Boktai 2**](https://retroachievements.org/Game/569) - [13](https://retroachievements.org/ticketmanager.php?g=569)
>[**More...**](https://retroachievements.org/ticketmanager.php?f=1)

Maybe something for displaying a ticket karma leaderboard, too 🤔

**Comment by lowlightdev** [comment]
i'll be taking a look at this :)

**Comment by meleu** [comment]
hey @lowlightdev , thanks for that! :heart: 

I'd recommend to wait a bit, though.

I'll try to add a ticket related endpoint in the web API in order to make it easier to get such info.

I'll let you know when it's ready. ;)

**Comment by meleu** [comment]
@televandalist 
I implemented a bit different from what you requested, but I hope it's still useful. See the announcement on discord.

@lowlightdev 
I got some free time last sunday and ended up implementing this, thanks anyways! :)
